[book]
authors = ["Rain"]
language = "en"
multilingual = false
src = "src"
theme = "theme"
title = "Rain's Rust CLI recommendations"
description = "Tips and best practices for writing and structuring Rust command-line programs."

[output.html]
default-theme = "rust"
git-repository-url = "https://github.com/sunshowers-code/rust-cli-recommendations"
edit-url-template = "https://github.com/sunshowers-code/rust-cli-recommendations/edit/main/{path}"
site-url = "https://rust-cli-recommendations.sunshowers.io"
no-section-label = true
