[book]
authors = ["Rain"]
language = "en"
multilingual = false
src = "src"
title = "Rain's Rust CLI recommendations"
description = "Covers recommendations for writing and structuring Rust command-line programs."

[output.html]
git-repository-url = "https://github.com/sunshowers-code/rust-cli-recommendations"
edit-url-template = "https://github.com/sunshowers-code/rust-cli-recommendations/edit/main/{path}"
site-url = "https://rust-cli-recommendations.sunshowers.io"
