[package]
name = "organizing-binary"
version = "0.1.0"
edition = "2021"

[lib]
name = "my_app"

[dependencies]
color-eyre = { version = "0.6.0", default-features = false }
clap = { version = "3.0.8", features = ["derive"] }
